### ISSUE TITLE
Some problems with reprocessing

### ISSUE THREAD

**Issue by leepinkz** [triple-Mu/AI-on-Board#1]
Hello, thanks for sharing, my model output is not quite the same as yours, can you please provide the following postprocess_yolov8 postprocessing source code from your triplemu-0.0.1-cp38-cp38-linux_aarch64.whl?

**Comment by leepinkz** [comment]
您好，请问可以提供triplemu-0.0.1-cp38-cp38-linux_aarch64.whl的后处理源码吗？

**Comment by QAZJH** [comment]
你好，当我在执行pip install triplemu-0.0.1-cp38-cp38-linux_aarch64.whl时候报错：ERROR: Wheel 'triplemu' located at /home/orangepi/yolov8_rknn/yolov8/AI-on-Board/Rockchip/python/yolov8/triplemu-0.0.1-cp38-cp38-linux_aarch64.whl is invalid.希望得到您的回复。

by the way，我在执行pip install rknn_toolkit_lite2-1.5.0-cp38-cp38-linux_aarch64.whl这一步的时候也报同样的错误，但是我在将文件替换为官方文件时（1.5.2版本）就可以成功执行

**Comment by triple-mu** [comment]
> 您好，请问可以提供triplemu-0.0.1-cp38-cp38-linux_aarch64.whl的后处理源码吗？

https://github.com/airockchip/rknn_model_zoo 官方的可以看看

**Comment by triple-mu** [comment]
> 你好，当我在执行pip install triplemu-0.0.1-cp38-cp38-linux_aarch64.whl时候报错：ERROR: Wheel 'triplemu' located at /home/orangepi/yolov8_rknn/yolov8/AI-on-Board/Rockchip/python/yolov8/triplemu-0.0.1-cp38-cp38-linux_aarch64.whl is invalid.希望得到您的回复。
> 
> by the way，我在执行pip install rknn_toolkit_lite2-1.5.0-cp38-cp38-linux_aarch64.whl这一步的时候也报同样的错误，但是我在将文件替换为官方文件时（1.5.2版本）就可以成功执行

本项目只在rk3588上测试过

**Comment by Hongboo-Li** [comment]
我在执行这一步的时候python onnx2rknn.py报错：
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 2012, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/rknn_base.py", line 384, in rknn.api.rknn_base.RKNNBase._generate_rknn
E build:   File "rknn/api/rknn_base.py", line 234, in rknn.api.rknn_base.RKNNBase._build_rknn
E build: ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/hbli/miniconda3/envs/rknn/lib/python3.8/site-packages/rknn/api/lib/linux-x86_64/cp38/librknnc.so)
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
Build model failed!
